version: '3.8'


services :
  pg_database:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: root
      POSTGRES_DB: geomeeting
      PGDATA: /var/lib/postgresql/data
    ports:
      - "443:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  sessions_cache:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis-cache/data:/data


